#!/bin/sh

# Hardcoded Default Settings
CONFIG_HW_FALLBACK="01"
CONFIG_COMPILATOR="gcc"
CONFIG_SOURCE_FILE="main.c"
CONFIG_COMPILED_BINARY="./a.out"
CONFIG_REF_PREFIX="./b3b36prg-hw"
CONFIG_REF_SUFFIX="-genref"
CONFIG_DEFAULT_LOOPS=30

# search upwards for user_settings.json
SEARCH_DIR="$(cd "$(dirname "$0")" && pwd)"
USER_FILE=""

# not using true as a precaution
for _ in `seq 1 6`; do
    # found set $USER_FILE to the found location
    if [ -f "$SEARCH_DIR/test_pubs_user_settings.json" ]; then
        USER_FILE="$SEARCH_DIR/test_pubs_user_settings.json"
        break
    fi
    
    if [ "$SEARCH_DIR" = "/" ]; then # hit the root exit
        break
    fi
    
    SEARCH_DIR="$(dirname "$SEARCH_DIR")" # take the parent directory
done

# Pure POSIX JSON Extractor
extract_json_value() {
    key="$1"
    file="$2"
    awk -F':' -v k="\"$key\"" '
    $1 ~ k {
        val = substr($0, index($0, $2))
        sub(/^[ \t]+/, "", val)
        sub(/,[ \t]*$/, "", val)
        sub(/^"/, "", val)
        sub(/"$/, "", val)
        print val
        exit
    }' "$file"
}

user_file_loaded=0
# Override defaults if user_settings.json exists
if [ -n "$USER_FILE" ]; then
    user_file_loaded=1 # set to true to display that loading was successful
    val=$(extract_json_value "hw_fallback" "$USER_FILE")
    [ -n "$val" ] && CONFIG_HW_FALLBACK="$val"

    val=$(extract_json_value "compilator" "$USER_FILE")
    [ -n "$val" ] && CONFIG_COMPILATOR="$val"

    val=$(extract_json_value "source_file" "$USER_FILE")
    [ -n "$val" ] && CONFIG_SOURCE_FILE="$val"

    val=$(extract_json_value "compiled_binary" "$USER_FILE")
    [ -n "$val" ] && CONFIG_COMPILED_BINARY="$val"

    val=$(extract_json_value "ref_prefix" "$USER_FILE")
    [ -n "$val" ] && CONFIG_REF_PREFIX="$val"

    val=$(extract_json_value "ref_suffix" "$USER_FILE")
    [ -n "$val" ] && CONFIG_REF_SUFFIX="$val"

    val=$(extract_json_value "default_loops" "$USER_FILE")
    [ -n "$val" ] && CONFIG_DEFAULT_LOOPS="$val"
fi

# Dynamic HW number extraction
SCRIPT_DIR="$PWD"
FOLDER_NAME="${SCRIPT_DIR##*/}"
HW=$(echo "$FOLDER_NAME" | sed 's/.*\(..\)$/\1/')

if [ -z "$HW" ]; then
    HW="$CONFIG_HW_FALLBACK"
fi

# Setup paths using configured variables (either the harcoded or the loaded ones)
PROGRAM_REF="${CONFIG_REF_PREFIX}${HW}${CONFIG_REF_SUFFIX}"
NC_PROGRAM_MY="$CONFIG_SOURCE_FILE"
PROGRAM_MY="$CONFIG_COMPILED_BINARY"
COMPILATOR="$CONFIG_COMPILATOR"

# used as bool
correct=1

# used by flags
hex_mode=0
random_mode=0
valgrind=""
compile=0
dump=0
input=0
large_random=0
loops="$CONFIG_DEFAULT_LOOPS"
number_of_correct=0
sum_runtimes=0
columns=$( tput cols )
side_by_side="-y --suppress-common-lines -W $columns"

# get the flags and make the corresponding vars true 
# what each flag does is clear from the config table below
while getopts "xrvcsdiR:" flag; do
    case "${flag}" in
        x) hex_mode=1 ;;
        r) random_mode=1;;
        v) valgrind="valgrind -q --leak-check=yes --log-file=valgrind_leak.log --error-exitcode=42"  ;;
        c) compile=1 ;;
        d) dump=1 ;;
        i) input=1 ;;
        R) loops=${OPTARG}
            random_mode=1 ;;
        s) side_by_side="" ;;
    esac
done

# nicely display what's on and what's off
echo "========================================"
echo "          TEST CONFIGURATION            "
echo "========================================"

printf " Compilation (-c)     : %s\n" "$([ "$compile" -eq 1 ] && echo "ON" || echo "OFF")"
printf " Valgrind (-v)        : %s\n" "$([ -n "$valgrind" ] && echo "ON" || echo "OFF")"
printf " Hex diff (-x)        : %s\n" "$([ "$hex_mode" -eq 1 ] && echo "ON" || echo "OFF")"
printf " Random (-r/-R)       : %s\n" "$([ "$random_mode" -eq 1 ] && echo "ON" || echo "OFF")"
printf " Entire dump (-d)     : %s\n" "$([ "$dump" -eq 1 ] && echo "ON" || echo "OFF")"
printf " Manual Input (-i)    : %s\n" "$([ "$input" -eq 1 ] && echo "ON" || echo "OFF")"
printf " Side by side (-s)    : %s\n" "$([ "$side_by_side" = "" ] && echo "OFF" || echo "ON")"
printf " Custom json settings : %s\n" "$([ "$user_file_loaded" -eq 1 ] && echo "ON" || echo "OFF")"

echo "========================================"
echo ""

# if desired compile the script
if [ $compile -eq 1 ]; then
    $COMPILATOR -g $NC_PROGRAM_MY || { echo "Compilation failed aborting"; exit 1; }
fi

if [ $input -eq 1 ] && [ $random_mode -eq 1 ]; then
    echo "Warning: random mode with manual input on -> only manual input"
fi

if [ $loops -lt 1 ]; then 
    echo Cannot loop for less than 1 time
fi

# radnom or pub mode based on the given flag, added manual input mode it is tuged together with random mode
# in a pub mode it compares the reference solution and mine and stops when they differ
if [ $random_mode -eq 1 ] || [ $input -eq 1 ]; then
    mkdir -p my_random_data #create folder for files generated by the random or single input solution 
    #(in random mode just the last file stays their)
    if echo "$loops" | grep -Eq '^[0-9]+$'
    then
        echo 
    else
        echo You did not input a number aborting...
        exit 1
    fi
    bar_width=40

    for i in `seq 1 $loops`
    do
        PROBLEM=my_random_data/hw$HW # custom naming
        MY_SOLUTION=my_random_data/my_hw$HW # custom naming
        # generate random input
        $PROGRAM_REF -generate > $PROBLEM.in 2>/dev/null

        # manual input, prompt for it
        if [ $input -eq 1 ]; then
            echo "Enter the test data (press Ctrl+D on a new line when finished): "
            cat > $PROBLEM.in # reads directly from the terminal
            echo "" # make it cleaner
        fi
        
        # get their solution to the problem
        $PROGRAM_REF < $PROBLEM.in > $PROBLEM.out 2>$PROBLEM.err

        start_time=$(date +%s%3N) #start timer
        # get my solution to the problem
        $valgrind $PROGRAM_MY < $PROBLEM.in > $MY_SOLUTION.out 2>$MY_SOLUTION.err
        
        valgrind_status=$? # catch last return value in this case from valgrind            
        end_time=$(date +%s%3N) # end timer
        run_time=$(($end_time - $start_time)) # final time
        
        # check valgrind error
        if [ "$valgrind_status" -eq 42 ]; then
            printf "\n Test $i memory leak detected:"
            cat valgrind_leak.log # show the valgrind error (it is put away to its own file to not collide with stderr)
            correct=0
        fi

        # compare the solutions normally and print the outcome
        diff $side_by_side $MY_SOLUTION.out $PROBLEM.out
        if ! [ $? -eq 0 ]; then
            correct=0
        fi
        diff $side_by_side $MY_SOLUTION.err $PROBLEM.err
        if ! [ $? -eq 0 ]; then
            correct=0
        fi

        if [ $correct -eq 1 ]; then
            # count parameters for statistics later
            number_of_correct=$((number_of_correct + 1 ))
            sum_runtimes=$((sum_runtimes + $run_time ))


            if [ $loops -lt 31 ]; then
                echo "Test $i is correct (${run_time}ms)"
            else            
            # progress bar
            percent=$(( number_of_correct * 100 / $loops ))
            completed_blocks=$(( percent * $bar_width / 100 ))
            bar=""
            c=0
            while [ $c -lt $completed_blocks ]; do
                bar="${bar}#"
                c=$(( c + 1 ))
            done

            printf "\r Random tests: [%-${bar_width}s] %d%% (%d/%d)" $bar $percent $number_of_correct $loops
            fi
        else
            if [ $dump -eq 1 ]; then
                echo
                echo "======================================================================"
                if [ "$side_by_side" = "" ]; then
                    cat $PROBLEM.out 
                    echo
                    cat $MY_SOLUTION.out
                else
                    pr -m -t -W $columns $PROBLEM.out $MY_SOLUTION.out
                fi
                echo "======================================================================"
                echo
            fi
        fi

        # if -x compare the solutions also in the hex form
        if [ $hex_mode -eq 1 ] && [ $correct -eq 0 ]; then
            hexdump -C $MY_SOLUTION.out > $MY_SOLUTION.out.hex
            hexdump -C $PROBLEM.out > $PROBLEM.out.hex
            echo
            echo "======================================================================"

            diff $side_by_side $MY_SOLUTION.out.hex $PROBLEM.out.hex
            echo "======================================================================"
        fi

        # stop at an incorrect solution or if single input is on
        if [ $correct -eq 0 ] || [ $input -eq 1 ]; then
            echo 
            echo "======================================================================"
            echo "TEST $i IS NOT CORRECT (YOUR OUTPUT IS ON THE LEFT OR ON THE TOP)"
            echo "======================================================================"
            echo
            break
        fi

    done
    echo ""
    echo The avarage runtime was/were $((sum_runtimes / $loops))ms

else
    mkdir -p my_data

    # loops through all files in data that ends .in
    for FILE in data/*.in;
    do
        # do this only if the file with the corresponding name exists
        if test -f $FILE; then
            number=$(echo "$FILE" | sed 's/^[^0-9]*\([0-9]*\).*$/\1/') # extracts first occurence of a number in the file name
            MY_SOLUTION=my_data/my_pub$number # where I want my solutions to be saved
            PROBLEM="${FILE%.in}" # strip away the .in
                    
            start_time=$(date +%s%3N) #start timer
            # run my program
            $valgrind $PROGRAM_MY < $PROBLEM.in > $MY_SOLUTION.out 2> $MY_SOLUTION.err
            valgrind_status=$? # catch valgrind return message
            end_time=$(date +%s%3N) # end timer
            run_time=$(($end_time - $start_time)) # final time


            # check valgrind error           
            if [ "$valgrind_status" -eq 42 ]; then
                printf "\n Pub test $number ("${PROBLEM##*/}") memory leak detected:"
                cat valgrind_leak.log # show the valgrind error
                correct=0
            fi

            # compare my solution with theirs and print the outcome, iff .err exists compare also against it
            diff $side_by_side $MY_SOLUTION.out $PROBLEM.out
            if ! [ $? -eq 0 ]; then 
                correct=0
            fi
            if test -f $PROBLEM.err; then                
                diff $side_by_side $MY_SOLUTION.err $PROBLEM.err
                if ! [ $? -eq 0 ]; then 
                    correct=0
                fi
            fi

            if [ $correct -eq 1 ]; then
                echo "Pub test $number ("${PROBLEM##*/}") is correct (${run_time}ms)"
            else
                correct=0
                if [ $dump -eq 1 ]; then
                    echo
                    echo "======================================================================"
                    if [ "$side_by_side" = "" ]; then
                        cat $PROBLEM.out 
                        echo
                        cat $MY_SOLUTION.out
                    else
                        pr -m -t -W $columns $PROBLEM.out $MY_SOLUTION.out
                    fi
                    echo "======================================================================"
                    echo
                fi
            fi

            # if -x compare it also in the hex form
            if [ $hex_mode -eq 1 ] && [ $correct -eq 0 ]; then
                hexdump -C $MY_SOLUTION.out > $MY_SOLUTION.out.hex

                if !(test -f $PROBLEM.out.hex); then
                    hexdump -C $PROBLEM.out > $PROBLEM.out.hex
                fi
                echo
                echo "======================================================================"
                diff $side_by_side $MY_SOLUTION.out.hex $PROBLEM.out.hex
                echo "======================================================================"

            fi

            # stop at an incorrect solution
            if [ $correct -eq 0 ]; then
                echo 
                echo "==============================================================================="
                echo "PUB TEST $number ("${PROBLEM##*/}") IS NOT CORRECT (YOUR OUTPUT IS ON THE LEFT OR ON THE TOP)"
                echo "==============================================================================="
                echo
                break
            fi
        else
            echo "Error loading files: The folder is probably empty"
            exit 1
        fi
    done
fi

# Clean up the hidden Valgrind log
rm -f valgrind_leak.log
